name: Build, Push, and Run Docker Image

on:
  push:
    branches: [ main ]  
jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t aromalgigi9/hello-docker-demo:latest .
          docker push aromalgigi9/hello-docker-demo:latest

      - name: Pull image from Docker Hub
        run: docker pull aromalgigi9/hello-docker-demo:latest

      - name: Run Docker container and show message
        run: docker run aromalgigi9/hello-docker-demo:latest
